name: Build, Test and Deploy the Hosted Widgets - Reusable workflow

on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
      REACT_APP_ENV_NAME:
        required: true
        type: string
      DEPLOY_TO_FLEEK:
        required: true
        type: boolean
      REACT_APP_RELEASE_TAG:
        required: false
        type: string
      REACT_APP_RELEASE_NAME:
        required: false
        type: string
    secrets:
      FLEEK_API_KEY:
        required: false
      REACT_APP_INFURA_IPFS_PROJECT_ID:
        required: false
      REACT_APP_INFURA_IPFS_PROJECT_SECRET:
        required: false
      REACT_APP_WALLET_CONNECT_PROJECT_ID:
        required: true
      REACT_APP_META_TX_API_KEY:
        required: true
      REACT_APP_META_TX_API_IDS:
        required: true
    outputs:
      JOB_LINT:
        value: ${{ jobs.build-test-deploy.outputs.jobLint }}
      JOB_BUILD:
        value: ${{ jobs.build-test-deploy.outputs.jobBuild }}
      DEPLOY_URL:
        value: ${{ jobs.build-test-deploy.outputs.deployUrl }}

jobs:
  build-test-deploy:
    name: Build, Test and Deploy the Hosted Widgets
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV_NAME: ${{ inputs.REACT_APP_ENV_NAME }}
      REACT_APP_RELEASE_TAG: ${{ inputs.REACT_APP_RELEASE_TAG }}
      REACT_APP_RELEASE_NAME: ${{ inputs.REACT_APP_RELEASE_NAME }}
      REACT_APP_INFURA_IPFS_PROJECT_ID: ${{ secrets.REACT_APP_INFURA_IPFS_PROJECT_ID }}
      REACT_APP_INFURA_IPFS_PROJECT_SECRET: ${{ secrets.REACT_APP_INFURA_IPFS_PROJECT_SECRET }}
      REACT_APP_WALLET_CONNECT_PROJECT_ID: ${{ secrets.REACT_APP_WALLET_CONNECT_PROJECT_ID }}
      REACT_APP_META_TX_API_KEY: ${{ secrets.REACT_APP_META_TX_API_KEY }}
      REACT_APP_META_TX_API_IDS: ${{ secrets.REACT_APP_META_TX_API_IDS }}
      REACT_APP_DEFAULT_TOKENS_LIST_TESTING: "[{\"symbol\":\"MATIC\",\"name\":\"MATIC\",\"address\":\"0x0000000000000000000000000000000000000000\",\"decimals\":\"18\"},{\"symbol\":\"WETH\",\"name\":\"Wrapped Ether\",\"address\":\"0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa\",\"decimals\":\"18\"},{\"symbol\":\"BOSON\",\"name\":\"Boson Token (PoS)\",\"address\":\"0x1f5431E8679630790E8EbA3a9b41d1BB4d41aeD0\",\"decimals\":\"18\"},{\"symbol\":\"USDC\",\"name\":\"Mumbai USD Coin\",\"address\":\"0xe6b8a5CF854791412c1f6EFC7CAf629f5Df1c747\",\"decimals\":\"6\"},{\"symbol\":\"DAI\",\"name\":\"DAI\",\"address\":\"0x001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f\",\"decimals\":\"18\"},{\"symbol\":\"USDT\",\"name\":\"Tether USD\",\"address\":\"0xA02f6adc7926efeBBd59Fd43A84f4E0c0c91e832\",\"decimals\":\"6\"}]"
      REACT_APP_DEFAULT_TOKENS_LIST_STAGING: "[{\"symbol\":\"MATIC\",\"name\":\"MATIC\",\"address\":\"0x0000000000000000000000000000000000000000\",\"decimals\":\"18\"},{\"symbol\":\"WETH\",\"name\":\"Wrapped Ether\",\"address\":\"0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa\",\"decimals\":\"18\"},{\"symbol\":\"BOSON\",\"name\":\"Boson Token (PoS)\",\"address\":\"0x1f5431E8679630790E8EbA3a9b41d1BB4d41aeD0\",\"decimals\":\"18\"},{\"symbol\":\"USDC\",\"name\":\"Mumbai USD Coin\",\"address\":\"0xe6b8a5CF854791412c1f6EFC7CAf629f5Df1c747\",\"decimals\":\"6\"},{\"symbol\":\"DAI\",\"name\":\"DAI\",\"address\":\"0x001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f\",\"decimals\":\"18\"},{\"symbol\":\"USDT\",\"name\":\"Tether USD\",\"address\":\"0xA02f6adc7926efeBBd59Fd43A84f4E0c0c91e832\",\"decimals\":\"6\"}]"
      REACT_APP_DEFAULT_TOKENS_LIST_PRODUCTION: "[{\"symbol\":\"MATIC\",\"name\":\"MATIC\",\"address\":\"0x0000000000000000000000000000000000000000\",\"decimals\":\"18\"},{\"symbol\":\"WETH\",\"name\":\"Wrapped Ether\",\"address\":\"0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619\",\"decimals\":\"18\"},{\"symbol\":\"BOSON\",\"name\":\"Boson Token (PoS)\",\"address\":\"0x9B3B0703D392321AD24338Ff1f846650437A43C9\",\"decimals\":\"18\"},{\"symbol\":\"USDC\",\"name\":\"USD Coin (PoS)\",\"address\":\"0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174\",\"decimals\":\"6\"},{\"symbol\":\"DAI\",\"name\":\"(PoS) Dai Stablecoin\",\"address\":\"0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063\",\"decimals\":\"18\"},{\"symbol\":\"USDT\",\"name\":\"(PoS) Tether USD\",\"address\":\"0xc2132D05D31c914a87C6611C10748AEb04B58e8F\",\"decimals\":\"6\"}]"
      REACT_APP_DEFAULT_DISPUTE_RESOLVER_ID_TESTING: "13"
      REACT_APP_DEFAULT_DISPUTE_RESOLVER_ID_STAGING: "2"
      REACT_APP_DEFAULT_DISPUTE_RESOLVER_ID_PRODUCTION: "1"
      REACT_APP_DEFAULT_DISPUTE_PERIOD_DAYS: "30"
      REACT_APP_DEFAULT_RESOLUTION_PERIOD_DAYS: "15"
      REACT_APP_CONTACT_SELLER_FOR_EXCHANGE_TESTING: "https://interface-test.on.fleek.co/#/chat/{id}"
      REACT_APP_CONTACT_SELLER_FOR_EXCHANGE_STAGING: "https://interface-staging.on.fleek.co/#/chat/{id}"
      REACT_APP_CONTACT_SELLER_FOR_EXCHANGE_PRODUCTION: "https://bosonapp.io/#/chat/{id}"
      REACT_APP_RAISE_DISPUTE_FOR_EXCHANGE_TESTING: "https://drcenter-test.on.fleek.co/#/exchange/{id}/raise-dispute"
      REACT_APP_RAISE_DISPUTE_FOR_EXCHANGE_STAGING: "https://drcenter-staging.on.fleek.co/#/exchange/{id}/raise-dispute"
      REACT_APP_RAISE_DISPUTE_FOR_EXCHANGE_PRODUCTION: "https://disputes.bosonprotocol.io/#/exchange/{id}/raise-dispute"
      REACT_APP_IPFS_GATEWAY: "https://bosonprotocol.infura-ipfs.io/ipfs"
      REACT_APP_BUYER_SELLER_AGREEMENT_TEMPLATE: "ipfs://QmQ8ZTmmRV15rFaWG9KRyjFRrpaD1o2sDwZoYiWgBaAto6"
      REACT_APP_RNFT_LICENSE_TEMPLATE: "ipfs://QmeVkdpKbfHKrPb9tXDXUoPEResEanGpcGANfAjb8bUQYT"
      REACT_APP_FAIR_EXCHANGE_POLICY_RULES: "ipfs://QmNqhFGr9NUEMqz3oQC7yUqJG9mt4NZEpV5MCeemVMTSRs"
    outputs:
      jobLint: ${{ steps.lint.outputs.pass }}
      jobBuild: ${{ steps.build.outputs.pass }}
      deployUrl: ${{ steps.deploy.outputs.deployUrl }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - run: npm ci
      - run: npm run prettier
      - run: npm run lint
      - id: lint
        run: echo "::set-output name=pass::success"
      - run: npm run build
      - id: build
        run: echo "::set-output name=pass::success"
      - name: (if 'staging' env) Copy contents from .fleek_staging.json to .fleek.json
        if: ${{ inputs.ENV_NAME == 'staging' }}
        run: mv .fleek_staging.json .fleek.json
      - name: (if 'production' env) Copy contents from .fleek_production.json to .fleek.json
        if: ${{ inputs.ENV_NAME == 'production' }}
        run: mv .fleek_production.json .fleek.json
      - name: Deploy via fleek
        if: ${{ inputs.DEPLOY_TO_FLEEK }}
        id: deploy
        run: npx @fleekhq/fleek-cli site:deploy
        env:
          FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
